### ISSUE TITLE
Breaks after Meteor 1.8.1 upgrade

### ISSUE THREAD

**Issue by claytonzaugg** [qualialabs/reval#33]
Here's what gets thrown on the command line

```
C:\Users\MyName\AppData\Local\.meteor\packages\promise\0.11.2\npm\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

TypeError: Cannot read property 'find' of undefined
    at Object.watchClientReload (packages/qualia:reval/server/reval.js:39:20)
    at Object.prepareCollection (packages/qualia:reval/server/reval.js:26:10)
    at Object.initialize (packages/qualia:reval/server/reval.js:12:10)
    at reval.js (packages/qualia:reval/server/reval.js:261:3)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at Module.moduleLink [as link] (C:\Users\MyName\AppData\Local\.meteor\packages\modules\0.13.0\npm\node_modules\reify\lib\runtime\index.js:38:38)
    at main.js (packages/qualia:reval/server/main.js:1:163)
    at fileEvaluate (packages\modules-runtime.js:336:7)
    at Module.require (packages\modules-runtime.js:238:14)
    at require (packages\modules-runtime.js:258:21)
    at C:\Users\MyName\sites\myProject\.meteor\local\build\programs\server\packages\qualia_reval.js:1452:15
    at C:\Users\MyName\sites\myProject\.meteor\local\build\programs\server\packages\qualia_reval.js:1457:3
    at C:\Users\MyName\sites\myProject\.meteor\local\build\programs\server\boot.js:419:36
    at Array.forEach (<anonymous>)
    at C:\Users\MyName\sites\myProject\.meteor\local\build\programs\server\boot.js:228:19
```

**Comment by claytonzaugg** [comment]
I've never really left feedback before, so I hope this is information you would be looking for. Let me know if you require anything further, because I really do enjoy using this plugin while developing, it makes for an easier time :)

**Comment by veered** [comment]
Sorry for the delay in responding! Could you please provide me with a simple Meteor app that reproduces the problem?
